title: Yiteng Guo's Homepage
page-top-title: Yiteng Guo
top-section-bg-text: Data Science
home-subtitle: Yiteng Guo&ensp;|&ensp;郭奕腾
copyright-text: '&copy; Yiteng Guo 2023-2026. All Rights Reserved.'
